import Head from 'next/head';
import Script from 'next/script'
import React, { createContext, useContext, useEffect, useState } from 'react';
import CartProduct from '../comps/cart';


export const CurrentPageContext = createContext(null)


export default function Home() {
    const [currentMenu, setCurrentMenu] = useState('Details');

    function changeMenu (newMenu) {
        setCurrentMenu(newMenu)
    }



  return (
    <div className='container'>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      
      </Head>
      <main>
        <div className='section-title-container'>
            <a>-Almost there</a>
            <p>Checkout</p>
        </div>
        <div className='checkout-page'>
            <CurrentPageContext.Provider value={currentMenu}>
            <div className='checkout-right-section'>
                <CheckoutProgressBar />
                <div className='checkout-menu-container'>
                    <CheckoutMenu goToMenu={changeMenu}/>
                </div>
                
            </div>
            
            </CurrentPageContext.Provider>
        </div>
      </main>
    </div>
  )
}

const CheckoutProgressBar = () => {
    const currentMenu = useContext(CurrentPageContext);
    const steps = ['Details', 'Shipping Mehod', 'Shipping Details', 'Payment Method', 'Payment Details', 'Thank You']
    const menuIndex = steps.indexOf(currentMenu)
    
    return ( <div className='checkout-progress-bar'>
    <div className={menuIndex >= 0 && 'active-progress'} ><p>1</p></div>
    <span className={menuIndex >= 1 && 'active-line'}></span>
    <div className={menuIndex >= 2 && 'active-progress'}><p>2</p></div>
    <span className={menuIndex >= 3 && 'active-line'}></span>
    <div className={menuIndex >= 4 && 'active-progress'}><p>3</p></div>
    <span className={menuIndex >= 5 && 'active-line'}></span>
    <div className={menuIndex >= 5 && 'active-progress'}><p>4</p></div>
</div> );
}
 


const CheckoutMenu = (props) => {
    
    const currentMenu  = useContext(CurrentPageContext);
    const [userEmail, setUserEmail] = useState("")
    const [userPassword, setUserPassword] = useState("")
    const [userName, setUserName] = useState("")
    const [userAddress, setUserAddress] = useState("")
    const [userCity, setUserCity] = useState("")
    const [userProvince, setUserProvince] = useState("")
    const [userPostalCode, setUserPostalCode] = useState("")
    const [userPhoneNumber, setUserPhoneNumber] = useState("")
    const [currentBasketLine, setCurrentBasketLine] = useState("")
    const [sdk, setSdk] = useState(false)
    

    function userLogin (event) {
        event.preventDefault()
        console.log(userEmail, userPassword, currentBasketLine)
        props.goToMenu('Shipping Details')
    }
    
    function shippingDetails (event) {
        event.preventDefault()
        console.log(userName, userCity, userAddress, userProvince, userPostalCode, userPhoneNumber)
        props.goToMenu('Payment Details')
    }

    const currentBasket = async () => {
        const token = localStorage.getItem("Token")
        const res = await fetch('https://the-bread-basket.herokuapp.com/api/basket/', {
        method: 'GET',
        headers: {
            'Content-Type': 'application/json',
            'Authorization': "Token " + token
        }
    });

    const data = await res.json();
    setCurrentBasketLine(data.url) 
}
   
    
    const placeOrder = async (event) => {
        const token = localStorage.getItem("Token")
        console.log(token)
        event.preventDefault()
        const res = await fetch('https://the-bread-basket.herokuapp.com/api/checkout/', {
        method: 'POST',
        body: JSON.stringify({
            basket : currentBasketLine,
            total : 100, 
            shipping_charge : {
                curency: "R",
                excl_tax: 0,
                tax: 0
            },
            shipping_address: {
                country: 'https://the-bread-basket.herokuapp.com/api/countries/ZA/',
                first_name: userName,
                last_name: "",
                line1 : userAddress,
                phone_number : userPhoneNumber,
                postcode : userPostalCode,
                state :userProvince,
                title: ""
            }   
        }),
        headers: {
            'Content-Type': 'application/json',
            'Authorization': "Token " + token
        }


    });
    const data = await res.json();
    console.log("submission info", data)
}

//    function paymentGateway () {
       
//     // sdk.inline({
//     //     layout: 'field',
//     //     ammountInCents: 55500,
//     //     curency: 'ZAR'
//     // })
//     // mount('#card-frame')
//     console.log(sdk.inline({
//         layout: 'field',
//         ammountInCents: 55500,
//         curency: 'ZAR'
//     }))
//    }

// useEffect(() => {
//     sdk && paymentGateway()
// }, [sdk])


useEffect(() => {
    currentBasket()
}, [])

    
    
    return ( 
        <div>
            <p className='checkout-menu-title'><i className='bi bi-chevron-left'></i>{currentMenu}</p>
           
{/* User Login Details */}

            {currentMenu === 'Details'  && <form onSubmit={userLogin}>
            <div className='login-inputs'>
                <div>
                    <input type='email' placeholder='Email address or phone number' onChange={(e) => setUserEmail(e.target.value)}/>
                </div>
                <div>
                    <input type='password' placeholder='Password' onChange={(e) => setUserPassword(e.target.value)}/>
                </div>
                
               </div>
               <div className='checkout-buttons'>
                    <button className='primary-button' type="submit">Sign In</button>
                    <button className='secondary-button'>Guest Checkout</button>
                </div>
                </form>}

{/* User Shipping details */}

                {currentMenu === 'Shipping Details'  && <form onSubmit={shippingDetails}>
            <div className='login-inputs'>
                <div>
                    <input name="fname" type='name' placeholder='Full Name' onChange={(e) => setUserName(e.target.value)}/>
                </div>
                <div>
                    <input type='address' placeholder='Address' onChange={(e) => setUserAddress(e.target.value)}/>
                </div>
                <span>
                    <input type='text' placeholder='City' onChange={(e) => setUserCity(e.target.value)}/>                   
                </span>
                <span>
                    <input type='text' placeholder='Province' onChange={(e) => setUserProvince(e.target.value)}/>                   
                </span>
                <span>
                    <input type='text' placeholder='Country' onChange={(e) => setUserPhoneNumber(e.target.value)}/>                   
                </span>
                <span>
                    <input type='text' placeholder='Postal Code' onChange={(e) => setUserPostalCode(e.target.value)}/>                   
                </span>
               </div>
               <div className='checkout-buttons'>
                    <button className='primary-button' type="submit">Continue</button>
                </div>
                </form>}

{/* User Payment Details */}
{/* <Script src="https://js.yoco.com/sdk/v1/yoco-sdk-web.js" onLoad={() => setSdk (new window.YocoSDK({ publicKey: 'pk_test_ed3c54a6g0ol69qa7f45' })) }/> */}
                
                {currentMenu === 'Payment Details'  && <div>
               
            <div className='login-inputs'>
                <div id="card-frame"></div>
                <div>
                    <input type='email' placeholder='Name'/>
                </div>
                <div>
                    <input type='email' placeholder='Card Number'/>
                </div>
                <span>
                    <input type='email' placeholder='Expiration(mm/yy)'/>                   
                </span>
                <span>
                    <input type='email' placeholder='Security code'/>                   
                </span>
               </div>
               <div className='checkout-buttons'>
                    <button onClick={placeOrder} className='primary-button'>Place Order</button>
                </div>
                </div>}

{/* Payment Thank You */}

{currentMenu === 'Thank You'  && <div>
            <div className='checkout-thank-you'>
                <p>Your order has been placed and a confirmation email has been sent to'user email', Your order  number is 'order number'. 
                please make a note of this reference or print this page and quote it in any communication with us reguarding your order.
                You can track the progress of your order in the user dashboard     
                 </p>
                 <a>Track Now</a>
               </div>
               <div className='checkout-buttons'>
                    <button onClick={() => props.goToMenu('Details')} className='primary-button'>Place Order</button>
                </div>
                </div>}
        </div>
     );
}


