import Head from 'next/head';
import React, { createContext, useContext, useState } from 'react';
import CartProduct from '../comps/cart';


export const CurrentPageContext = createContext(null)


export default function Home() {
    const [currentMenu, setCurrentMenu] = useState('Details');

    function changeMenu (newMenu) {
        setCurrentMenu(newMenu)
    }

  return (
    <div className='container'>
      <Head>
        <title>Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <div className='section-title-container'>
            <a>-Almost there</a>
            <p>Checkout</p>
        </div>
        <div className='checkout-page'>
            <CurrentPageContext.Provider value={currentMenu}>
            <div className='checkout-right-section'>
                <CheckoutProgressBar />
                <div className='checkout-menu-container'>
                    <CheckoutMenu event={changeMenu}/>
                </div>
                
            </div>
            
            </CurrentPageContext.Provider>
        </div>
      </body>
    </div>
  )
}

const CheckoutProgressBar = () => {
    const currentMenu = useContext(CurrentPageContext);
    const steps = ['Details', 'Shipping Mehod', 'Shipping Details', 'Payment Method', 'Payment Details', 'Thank You']
    const menuIndex = steps.indexOf(currentMenu)
    
    return ( <div className='checkout-progress-bar'>
    <div className={menuIndex >= 0 && 'active-progress'} ><p>1</p></div>
    <span className={menuIndex >= 1 && 'active-line'}></span>
    <div className={menuIndex >= 2 && 'active-progress'}><p>2</p></div>
    <span className={menuIndex >= 3 && 'active-line'}></span>
    <div className={menuIndex >= 4 && 'active-progress'}><p>3</p></div>
    <span className={menuIndex >= 5 && 'active-line'}></span>
    <div className={menuIndex >= 5 && 'active-progress'}><p>4</p></div>
</div> );
}
 


const CheckoutMenu = (props) => {
    const currentMenu  = useContext(CurrentPageContext);

    return ( 
        <div>
            <p className='checkout-menu-title'><i className='bi bi-chevron-left'></i>{currentMenu}</p>
           
{/* User Login Details */}

            {currentMenu === 'Details'  && <div>
            <div className='login-inputs'>
                <div>
                    <input type='email' placeholder='Email address or phone number'/>
                </div>
                <div>
                    <input type='password' placeholder='Password'/>
                </div>
                
               </div>
               <div className='checkout-buttons'>
                    <button className='primary-button' onClick={() => props.event('Shipping Details')}>Sign In</button>
                    <button className='secondary-button'>Guest Checkout</button>
                </div>
                </div>}

{/* User Shipping details */}

                {currentMenu === 'Shipping Details'  && <div>
            <div className='login-inputs'>
                <div>
                    <input type='name' placeholder='Full Name'/>
                </div>
                <div>
                    <input type='address' placeholder='Street Name'/>
                </div>
                <span>
                    <input type='text' placeholder='City'/>                   
                </span>
                <span>
                    <input type='text' placeholder='Province'/>                   
                </span>
                <span>
                    <input type='text' placeholder='Country'/>                   
                </span>
                <span>
                    <input type='zip-code' placeholder='Zip Code'/>                   
                </span>
               </div>
               <div className='checkout-buttons'>
                    <button className='primary-button' onClick={() => props.event('Payment Details')}>Continue</button>
                </div>
                </div>}

{/* User Payment Details */}

                {currentMenu === 'Payment Details'  && <div>
            <div className='login-inputs'>
                <div>
                    <input type='email' placeholder='Name'/>
                </div>
                <div>
                    <input type='email' placeholder='Card Number'/>
                </div>
                <span>
                    <input type='email' placeholder='Expiration(mm/yy)'/>                   
                </span>
                <span>
                    <input type='email' placeholder='Security code'/>                   
                </span>
               </div>
               <div className='checkout-buttons'>
                    <button onClick={() => props.event('Thank You')} className='primary-button'>Place Order</button>
                </div>
                </div>}

{/* Payment Thank You */}

{currentMenu === 'Thank You'  && <div>
            <div className='checkout-thank-you'>
                <p>Your order has been placed and a confirmation email has been sent to'user email', Your order  number is 'order number'. 
                please make a note of this reference or print this page and quote it in any communication with us reguarding your order.
                You can track the progress of your order in the user dashboard     
                 </p>
                 <a>Track Now</a>
               </div>
               <div className='checkout-buttons'>
                    <button onClick={() => props.event('Details')} className='primary-button'>Place Order</button>
                </div>
                </div>}
        </div>
     );
}
 




