import Head from 'next/head';
import React, { useState } from 'react';
import Billboard from '../comps/billboard';
import CategoryCardSection from '../comps/categoryCards';
import ProductCardSection from '../comps/productCards';


export default function Home() {
  
  return (
    <div className='container'>
      <Head>
        <title>All your favorite Zimbabwean products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Billboard billboardTitle='All your favorite Zimbabwean products' callToAction='Shop Now'>
                <img id='billboardCerevita' className='jumbotron-image' src="/img/cerevita_choco_and_malt.png"/>
                <img id='billboardMazoe' className='jumbotron-image' src="/img/mazoe_orange.png"/>
                <img id='billboardPfuko' className='jumbotron-image' src="/img/pfuko_maheu_original.png"/>
                <img id='billboardLyons' className='jumbotron-image' src="/img/lyons_peanut_butter_small.png"/>
                <img id='billboardRabroy' className='jumbotron-image' src="/img/rabroy_tomatoe_sauce.png"/>
      </Billboard>
      <CategoryCardSection/>
      <ProductCardSection title='Explore our Top Selling Products' linkTitle='-Top Selling Products'/>
      <Billboard billboardTitle='All these great savings on your mobile' callToAction='Download App'>
          <img id='macbook' className='jumbotron-image' src="/img/macbook.png"/>
          <img id='iphone' className='jumbotron-image' src="/img/iphone.png"/>
      </Billboard>
      <ProductCardSection title='Recently Viewed Items' linkTitle='-Recently Viewed Items'/>
    </div>
  )
}



